In [11]:
import polars as pl

In [12]:
df = pl.read_csv('/content/home_credit/csv_files/train/train_base.csv')
df

shape: (1_526_659, 5)
┌─────────┬───────────────┬────────┬──────────┬────────┐
│ case_id ┆ date_decision ┆ MONTH  ┆ WEEK_NUM ┆ target │
│ ---     ┆ ---           ┆ ---    ┆ ---      ┆ ---    │
│ i64     ┆ str           ┆ i64    ┆ i64      ┆ i64    │
╞═════════╪═══════════════╪════════╪══════════╪════════╡
│ 0       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 1       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 2       ┆ 2019-01-04    ┆ 201901 ┆ 0        ┆ 0      │
│ 3       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 4       ┆ 2019-01-04    ┆ 201901 ┆ 0        ┆ 1      │
│ …       ┆ …             ┆ …      ┆ …        ┆ …      │
│ 2703450 ┆ 2020-10-05    ┆ 202010 ┆ 91       ┆ 0      │
│ 2703451 ┆ 2020-10-05    ┆ 202010 ┆ 91       ┆ 0      │
│ 2703452 ┆ 2020-10-05    ┆ 202010 ┆ 91       ┆ 0      │
│ 2703453 ┆ 2020-10-05    ┆ 202010 ┆ 91       ┆ 0      │
│ 2703454 ┆ 2020-10-05    ┆ 202010 ┆ 91       ┆ 0      │
└─────────┴───────────────┴────────┴──────────┴────────┘

In [17]:
df.shape

(1526659, 5)

In [18]:
df.describe()

shape: (9, 6)
┌────────────┬───────────────┬───────────────┬───────────────┬────────────┬────────────┐
│ statistic  ┆ case_id       ┆ date_decision ┆ MONTH         ┆ WEEK_NUM   ┆ target     │
│ ---        ┆ ---           ┆ ---           ┆ ---           ┆ ---        ┆ ---        │
│ str        ┆ f64           ┆ str           ┆ f64           ┆ f64        ┆ f64        │
╞════════════╪═══════════════╪═══════════════╪═══════════════╪════════════╪════════════╡
│ count      ┆ 1.526659e6    ┆ 1526659       ┆ 1.526659e6    ┆ 1.526659e6 ┆ 1.526659e6 │
│ null_count ┆ 0.0           ┆ 0             ┆ 0.0           ┆ 0.0        ┆ 0.0        │
│ mean       ┆ 1.2861e6      ┆ null          ┆ 201936.287982 ┆ 40.769036  ┆ 0.031437   │
│ std        ┆ 718946.592285 ┆ null          ┆ 44.735975     ┆ 23.797981  ┆ 0.174496   │
│ min        ┆ 0.0           ┆ 2019-01-01    ┆ 201901.0      ┆ 0.0        ┆ 0.0        │
│ 25%        ┆ 766198.0      ┆ null          ┆ 201906.0      ┆ 23.0       ┆ 0.0        │
│ 50%        ┆ 1.357358e6    ┆ null          ┆ 201910.0      ┆ 40.0       ┆ 0.0        │
│ 75%        ┆ 1.739023e6    ┆ null          ┆ 202001.0      ┆ 55.0       ┆ 0.0        │
│ max        ┆ 2.703454e6    ┆ 2020-10-05    ┆ 202010.0      ┆ 91.0       ┆ 1.0        │
└────────────┴───────────────┴───────────────┴───────────────┴────────────┴────────────┘

In [19]:
df.dtypes

[Int64, String, Int64, Int64, Int64]

In [20]:
df.schema

Schema([('case_id', Int64),
        ('date_decision', String),
        ('MONTH', Int64),
        ('WEEK_NUM', Int64),
        ('target', Int64)])